version: "3.7"

services: 
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres